/*
 * Multiple Allele Code Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cz.esgaltur.hlavalidator.hlavalidator.nmdp_web_service.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * AlleleResponseItem
 */
@JsonPropertyOrder({
        AlleleResponseItem.JSON_PROPERTY_OLD_NAME,
        AlleleResponseItem.JSON_PROPERTY_OLD_NAME_STATUS,
        AlleleResponseItem.JSON_PROPERTY_EXPANDED,
        AlleleResponseItem.JSON_PROPERTY_TRANSFORMATION_REASON
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-26T01:59:51.225722100+01:00[Europe/Prague]")
public class AlleleResponseItem {
  public static final String JSON_PROPERTY_OLD_NAME = "oldName";
  public static final String JSON_PROPERTY_OLD_NAME_STATUS = "oldNameStatus";
  public static final String JSON_PROPERTY_EXPANDED = "expanded";
  public static final String JSON_PROPERTY_TRANSFORMATION_REASON = "transformationReason";
  private String oldName;
  private String oldNameStatus;
  private String expanded;
  private String transformationReason;


  public AlleleResponseItem oldName(String oldName) {

    this.oldName = oldName;
    return this;
  }

  /**
   * If a transformation is done, the original value
   *
   * @return oldName
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If a transformation is done, the original value")
  @JsonProperty(JSON_PROPERTY_OLD_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getOldName() {
    return oldName;
  }


  public void setOldName(String oldName) {
    this.oldName = oldName;
  }


  public AlleleResponseItem oldNameStatus(String oldNameStatus) {

    this.oldNameStatus = oldNameStatus;
    return this;
  }

  /**
   * Get oldNameStatus
   *
   * @return oldNameStatus
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_OLD_NAME_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getOldNameStatus() {
    return oldNameStatus;
  }


  public void setOldNameStatus(String oldNameStatus) {
    this.oldNameStatus = oldNameStatus;
  }


  public AlleleResponseItem expanded(String expanded) {

    this.expanded = expanded;
    return this;
  }

  /**
   * The full allele name used for display.
   *
   * @return expanded
   **/
  @ApiModelProperty(required = true, value = "The full allele name used for display.")
  @JsonProperty(JSON_PROPERTY_EXPANDED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getExpanded() {
    return expanded;
  }


  public void setExpanded(String expanded) {
    this.expanded = expanded;
  }


  public AlleleResponseItem transformationReason(String transformationReason) {

    this.transformationReason = transformationReason;
    return this;
  }

  /**
   * The code for the transformation performed.   * DISPLAYEXP - Added, updated, or removed an expression character   * DELRENAME - Transformed a deleted or renamed allele
   *
   * @return transformationReason
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The code for the transformation performed.   * DISPLAYEXP - Added, updated, or removed an expression character   * DELRENAME - Transformed a deleted or renamed allele ")
  @JsonProperty(JSON_PROPERTY_TRANSFORMATION_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTransformationReason() {
    return transformationReason;
  }


  public void setTransformationReason(String transformationReason) {
    this.transformationReason = transformationReason;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlleleResponseItem alleleResponseItem = (AlleleResponseItem) o;
    return Objects.equals(this.oldName, alleleResponseItem.oldName) &&
            Objects.equals(this.oldNameStatus, alleleResponseItem.oldNameStatus) &&
            Objects.equals(this.expanded, alleleResponseItem.expanded) &&
            Objects.equals(this.transformationReason, alleleResponseItem.transformationReason);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oldName, oldNameStatus, expanded, transformationReason);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlleleResponseItem {\n");
    sb.append("    oldName: ").append(toIndentedString(oldName)).append("\n");
    sb.append("    oldNameStatus: ").append(toIndentedString(oldNameStatus)).append("\n");
    sb.append("    expanded: ").append(toIndentedString(expanded)).append("\n");
    sb.append("    transformationReason: ").append(toIndentedString(transformationReason)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

