/*
 * Multiple Allele Code Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cz.esgaltur.hlavalidator.hlavalidator.nmdp_web_service.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A transformed multiple allele code designation like \&quot;HLA-A*01:AB\&quot;
 */
@ApiModel(description = "A transformed multiple allele code designation like \"HLA-A*01:AB\"")
@JsonPropertyOrder({
        TransformedMacd.JSON_PROPERTY_MACD,
        TransformedMacd.JSON_PROPERTY_TRANSFORMATIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-26T01:59:51.225722100+01:00[Europe/Prague]")
public class TransformedMacd {
  public static final String JSON_PROPERTY_MACD = "macd";
  public static final String JSON_PROPERTY_TRANSFORMATIONS = "transformations";
  private String macd;
  private List<AlleleResponseItem> transformations = new ArrayList<AlleleResponseItem>();


  public TransformedMacd macd(String macd) {

    this.macd = macd;
    return this;
  }

  /**
   * Get macd
   *
   * @return macd
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_MACD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMacd() {
    return macd;
  }


  public void setMacd(String macd) {
    this.macd = macd;
  }


  public TransformedMacd transformations(List<AlleleResponseItem> transformations) {

    this.transformations = transformations;
    return this;
  }

  public TransformedMacd addTransformationsItem(AlleleResponseItem transformationsItem) {
    this.transformations.add(transformationsItem);
    return this;
  }

  /**
   * Get transformations
   *
   * @return transformations
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TRANSFORMATIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<AlleleResponseItem> getTransformations() {
    return transformations;
  }


  public void setTransformations(List<AlleleResponseItem> transformations) {
    this.transformations = transformations;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransformedMacd transformedMacd = (TransformedMacd) o;
    return Objects.equals(this.macd, transformedMacd.macd) &&
            Objects.equals(this.transformations, transformedMacd.transformations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(macd, transformations);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransformedMacd {\n");
    sb.append("    macd: ").append(toIndentedString(macd)).append("\n");
    sb.append("    transformations: ").append(toIndentedString(transformations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

