/*
 * Multiple Allele Code Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cz.sosnovich.hlavalidator.hlavalidator.nmdp_web_service.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * A validation condition for a single allele
 */
@ApiModel(description = "A validation condition for a single allele")
@JsonPropertyOrder({
        AlleleValidationCondition.JSON_PROPERTY_CODE,
        AlleleValidationCondition.JSON_PROPERTY_IMGT_HLA_RELEASE,
        AlleleValidationCondition.JSON_PROPERTY_ITEM_VALUE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-26T01:59:51.225722100+01:00[Europe/Prague]")
public class AlleleValidationCondition {
  public static final String JSON_PROPERTY_CODE = "code";
  public static final String JSON_PROPERTY_IMGT_HLA_RELEASE = "imgtHlaRelease";
  public static final String JSON_PROPERTY_ITEM_VALUE = "itemValue";
  private String code;
  private String imgtHlaRelease;
  private String itemValue;


  public AlleleValidationCondition code(String code) {

    this.code = code;
    return this;
  }

  /**
   * Symbolic code for the condition   * DELETE - The original allele was deleted   * RENAME - The original allele has been renamed   * INVALID - The allele is invalid (never existed)   * DEPRECATED - The allele has been deleted/renamed, but is temporarily still valid
   *
   * @return code
   **/
  @ApiModelProperty(required = true, value = "Symbolic code for the condition   * DELETE - The original allele was deleted   * RENAME - The original allele has been renamed   * INVALID - The allele is invalid (never existed)   * DEPRECATED - The allele has been deleted/renamed, but is temporarily still valid ")
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    this.code = code;
  }


  public AlleleValidationCondition imgtHlaRelease(String imgtHlaRelease) {

    this.imgtHlaRelease = imgtHlaRelease;
    return this;
  }

  /**
   * IMGT HLA Release version for the condition
   *
   * @return imgtHlaRelease
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "IMGT HLA Release version for the condition")
  @JsonProperty(JSON_PROPERTY_IMGT_HLA_RELEASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getImgtHlaRelease() {
    return imgtHlaRelease;
  }


  public void setImgtHlaRelease(String imgtHlaRelease) {
    this.imgtHlaRelease = imgtHlaRelease;
  }


  public AlleleValidationCondition itemValue(String itemValue) {

    this.itemValue = itemValue;
    return this;
  }

  /**
   * Allele or value associated with response code
   *
   * @return itemValue
   **/
  @ApiModelProperty(required = true, value = "Allele or value associated with response code")
  @JsonProperty(JSON_PROPERTY_ITEM_VALUE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getItemValue() {
    return itemValue;
  }


  public void setItemValue(String itemValue) {
    this.itemValue = itemValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AlleleValidationCondition alleleValidationCondition = (AlleleValidationCondition) o;
    return Objects.equals(this.code, alleleValidationCondition.code) &&
            Objects.equals(this.imgtHlaRelease, alleleValidationCondition.imgtHlaRelease) &&
            Objects.equals(this.itemValue, alleleValidationCondition.itemValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, imgtHlaRelease, itemValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlleleValidationCondition {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    imgtHlaRelease: ").append(toIndentedString(imgtHlaRelease)).append("\n");
    sb.append("    itemValue: ").append(toIndentedString(itemValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

