/*
 * Multiple Allele Code Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cz.sosnovich.hlavalidator.hlavalidator.nmdp_web_service.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * A decoded typing like \&quot;HLA-A*01:AB\&quot;
 */
@ApiModel(description = "A decoded typing like \"HLA-A*01:AB\"")
@JsonPropertyOrder({
        DecodedTyping.JSON_PROPERTY_TYPING,
        DecodedTyping.JSON_PROPERTY_ALLELE_STRING,
        DecodedTyping.JSON_PROPERTY_HTTP_STATUS,
        DecodedTyping.JSON_PROPERTY_ERROR_MSG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-26T01:59:51.225722100+01:00[Europe/Prague]")
public class DecodedTyping {
  public static final String JSON_PROPERTY_TYPING = "typing";
  public static final String JSON_PROPERTY_ALLELE_STRING = "alleleString";
  public static final String JSON_PROPERTY_HTTP_STATUS = "httpStatus";
  public static final String JSON_PROPERTY_ERROR_MSG = "errorMsg";
  private String typing;
  private String alleleString;
  private Integer httpStatus;
  private String errorMsg;


  public DecodedTyping typing(String typing) {

    this.typing = typing;
    return this;
  }

  /**
   * Get typing
   *
   * @return typing
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTyping() {
    return typing;
  }


  public void setTyping(String typing) {
    this.typing = typing;
  }


  public DecodedTyping alleleString(String alleleString) {

    this.alleleString = alleleString;
    return this;
  }

  /**
   * Get alleleString
   *
   * @return alleleString
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ALLELE_STRING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAlleleString() {
    return alleleString;
  }


  public void setAlleleString(String alleleString) {
    this.alleleString = alleleString;
  }


  public DecodedTyping httpStatus(Integer httpStatus) {

    this.httpStatus = httpStatus;
    return this;
  }

  /**
   * Get httpStatus
   *
   * @return httpStatus
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_HTTP_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getHttpStatus() {
    return httpStatus;
  }


  public void setHttpStatus(Integer httpStatus) {
    this.httpStatus = httpStatus;
  }


  public DecodedTyping errorMsg(String errorMsg) {

    this.errorMsg = errorMsg;
    return this;
  }

  /**
   * Get errorMsg
   *
   * @return errorMsg
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR_MSG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorMsg() {
    return errorMsg;
  }


  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DecodedTyping decodedTyping = (DecodedTyping) o;
    return Objects.equals(this.typing, decodedTyping.typing) &&
            Objects.equals(this.alleleString, decodedTyping.alleleString) &&
            Objects.equals(this.httpStatus, decodedTyping.httpStatus) &&
            Objects.equals(this.errorMsg, decodedTyping.errorMsg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typing, alleleString, httpStatus, errorMsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DecodedTyping {\n");
    sb.append("    typing: ").append(toIndentedString(typing)).append("\n");
    sb.append("    alleleString: ").append(toIndentedString(alleleString)).append("\n");
    sb.append("    httpStatus: ").append(toIndentedString(httpStatus)).append("\n");
    sb.append("    errorMsg: ").append(toIndentedString(errorMsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

