/*
 * Multiple Allele Code Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cz.esgaltur.hlavalidator.hlavalidator.nmdp.nmdp_web_service.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * A validated typing like \&quot;HLA-A*01:AB\&quot;
 */
@ApiModel(description = "A validated typing like \"HLA-A*01:AB\"")
@JsonPropertyOrder({
        ValidatedTyping.JSON_PROPERTY_TYPING,
        ValidatedTyping.JSON_PROPERTY_VALIDATION_RESULT,
        ValidatedTyping.JSON_PROPERTY_HTTP_STATUS,
        ValidatedTyping.JSON_PROPERTY_ERROR_MSG
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-12-26T01:59:51.225722100+01:00[Europe/Prague]")
public class ValidatedTyping {
  public static final String JSON_PROPERTY_TYPING = "typing";
  public static final String JSON_PROPERTY_VALIDATION_RESULT = "validationResult";
  public static final String JSON_PROPERTY_HTTP_STATUS = "httpStatus";
  public static final String JSON_PROPERTY_ERROR_MSG = "errorMsg";
  private String typing;
  private ValidatedTypingValidationResultOneOf validationResult = null;
  private Integer httpStatus;
  private String errorMsg;


  public ValidatedTyping typing(String typing) {

    this.typing = typing;
    return this;
  }

  /**
   * Get typing
   *
   * @return typing
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TYPING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTyping() {
    return typing;
  }


  public void setTyping(String typing) {
    this.typing = typing;
  }


  public ValidatedTyping validationResult(ValidatedTypingValidationResultOneOf validationResult) {

    this.validationResult = validationResult;
    return this;
  }

  /**
   * Get validationResult
   *
   * @return validationResult
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_VALIDATION_RESULT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ValidatedTypingValidationResultOneOf getValidationResult() {
    return validationResult;
  }


  public void setValidationResult(ValidatedTypingValidationResultOneOf validationResult) {
    this.validationResult = validationResult;
  }


  public ValidatedTyping httpStatus(Integer httpStatus) {

    this.httpStatus = httpStatus;
    return this;
  }

  /**
   * Get httpStatus
   *
   * @return httpStatus
   **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_HTTP_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getHttpStatus() {
    return httpStatus;
  }


  public void setHttpStatus(Integer httpStatus) {
    this.httpStatus = httpStatus;
  }


  public ValidatedTyping errorMsg(String errorMsg) {

    this.errorMsg = errorMsg;
    return this;
  }

  /**
   * Get errorMsg
   *
   * @return errorMsg
   **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ERROR_MSG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorMsg() {
    return errorMsg;
  }


  public void setErrorMsg(String errorMsg) {
    this.errorMsg = errorMsg;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidatedTyping validatedTyping = (ValidatedTyping) o;
    return Objects.equals(this.typing, validatedTyping.typing) &&
            Objects.equals(this.validationResult, validatedTyping.validationResult) &&
            Objects.equals(this.httpStatus, validatedTyping.httpStatus) &&
            Objects.equals(this.errorMsg, validatedTyping.errorMsg);
  }

  @Override
  public int hashCode() {
    return Objects.hash(typing, validationResult, httpStatus, errorMsg);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidatedTyping {\n");
    sb.append("    typing: ").append(toIndentedString(typing)).append("\n");
    sb.append("    validationResult: ").append(toIndentedString(validationResult)).append("\n");
    sb.append("    httpStatus: ").append(toIndentedString(httpStatus)).append("\n");
    sb.append("    errorMsg: ").append(toIndentedString(errorMsg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

